// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import ElementRemovalController from "./element_removal_controller"
application.register("element-removal", ElementRemovalController)

import CopyToClipboardController from "./copy_to_clipboard_controller"
application.register("copy-to-clipboard", CopyToClipboardController)

import ButtonLoadingController from "./button_loading_controller"
application.register("button-loading", ButtonLoadingController)
